Repository queens-py/queens, pull requests merged in 2024-12, with the labels that each got.

#81 Change bibkey in readme
  README.md
Labels: high priority

#84 Use main branch for QUEENS logo
  README.md
Labels: minor: refactor

#86 Add workflow to build and deploy the documentation to github pages
  .github/actions/create_python_environment/action.yml
  .github/workflows/documentation.yml
  .github/workflows/tests_local.yml
  doc/source/conf.py
  doc/source/index.rst
Labels: topic: documentation
