Repository queens-py/queens, pull requests merged in 2025-02, with the labels that each got.

#109 Set unit and intergrations test as default pytest marker
  pyproject.toml
Labels: minor: refactor

#108 docs: Describe post-installation testing
  doc/source/_ext/templates/intro.md.j2
Labels: minor: documentation

#112 refactor(main): add info for users to consider using the script workflow
  queens/main.py
Labels: minor: quickfix

#116 ci: fix workflow rules
  .gitlab/.gitlab-ci.yml
Labels: minor: quickfix

#139 fix: 4C input DAMPING parameter
  tests/input_files/third_party/fourc/coarse_plate_dirichlet_template.dat
  tests/input_files/third_party/fourc/solid_runtime_hex8.dat
  tests/integration_tests/fourc/test_fourc_mc.py
  tests/integration_tests/fourc/test_fourc_mc_random_field_ensight.py
Labels: minor: quickfix
